# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # Defina a branch que deve acionar o pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get update
    sudo apt-get install php  # Instale o PHP ou a versão específica que você precisa
    sudo apt-get install composer  # Instale o Composer para gerenciar as dependências do Drupal
  displayName: 'Instalar PHP e Composer'

- script: |
    #composer install  # Execute comandos específicos para o seu projeto Drupal, como instalar módulos
    #drush updatedb  # Atualize o banco de dados, se necessário
    drush cr  # Limpe o cache do Drupal
    composer require drush/drush
  displayName: 'instalar drupal'

# Adicione mais etapas conforme necessário para compilar, testar e implantar seu projeto Drupal.

